### ISSUE TITLE
Let's check for plugins that are doing illegal things

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#13]
- [x] Trying to manipulate protocols API
- [x] Trying to remove listeners
- [ ] Trying to require core files
- [ ] Trying to change settings

Please add to the list if you have found other things that shouldn't be possible, also this issue is a discussion on how to do this

**Comment by boltgolt** [comment]
Probably going to find that i've done close to nothing security wise. We should give every plugin its own bot object/emitter.

**Comment by Nickforall** [comment]
Don't worry, `roadmap` issues are long-term issues that take a lot of time. I just wanted to have this issue up, so we can have this in mind while we are coding new features.

**Comment by boltgolt** [comment]
it's not possible to block access to core files or settings.json, unfortunately. we could stop access to fs altogether but that would limit plugins immensely. maybe add so kind of permission system later on?
