### ISSUE TITLE
Code cleanup and review skype meeting

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#14]
- [ ] Add more to the terminal handler, and move protocol related things from there
- [ ] Add more functionalities to the terminal API
- [ ] clean up the SPM command code, it's buggy and horrible to work with
- [ ] Document all functions, all of them!
- [ ] Check for duplicate or unreachable code
- [ ] Plugin work
  - [ ] Discuss how we are going to restructure the plugin manager
  - [ ] Discuss plugin security
- [ ] Design and create a universal format for `meta` object in the bot message even

Please add more if you come up with anything.

**Comment by Nickforall** [comment]
Added new tasks.

**Comment by Nickforall** [comment]
Added
- Design and create a universal format for `meta` object in the bot message event

**Comment by Nickforall** [comment]
This issue is closed since it became irrelevant due to a small 'restart' of Squadbot.

Cheers,
Nick
