### ISSUE TITLE
Generate a new settings.json on initial start

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#3]
So creating a settings.json is a bit of effort now, we want to 'automate' this process on first start.
- [ ] Move standard profile picture to settings.json
- [ ] Create an empty file with all the required variables
- [ ] Ask for commandline input
  - [x] Protocol (Whatsapp etc.)
  - [ ] if whatsapp ask for phone number
  - [ ] if whatsapp ask for home group 
  - [ ] if whatsapp ask for password
  - [ ] ask for display name
  - [ ] give a link to the settings.json docs

**Note:** I only wrote about whatsapp yet, since this is the only project we are supporting at the moment

**Comment by boltgolt** [comment]
Everything after "Protocol (Whatsapp etc.)" should be done in the exports.init function, not by index.js. Also, try `node squadbot whatsapp`.

**Comment by Nickforall** [comment]
Due to the change in the squadbot package manager, this issue became irrelevant.

Settings now come with a protocol package, and are safe enough to commit, since they won't contain any secret information.
